name: build-docker
on: [push]

jobs: 
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Récupérer la dernière version publiée
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/remylt/cicd-tuto/tags" | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+$' | sort -Vr | head -n 1)
          echo "Dernière version trouvée : $LATEST_VERSION"
          if [[ -z "$LATEST_VERSION" ]]; then
            NEW_VERSION="1.0"
          else
            MAJOR=$(echo $LATEST_VERSION | cut -d. -f1)
            MINOR=$(echo $LATEST_VERSION | cut -d. -f2)
            NEW_VERSION="$MAJOR.$(($MINOR + 1))"
          fi
          echo "Nouvelle version : $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: List files
        run: ls -la

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: List Docker images
        run: docker images

      - name: Taguer l'image avec la nouvelle version
        run: |
          docker tag my-image:latest remylt/cicd-tuto:latest
          docker tag my-image:latest remylt/cicd-tuto:$VERSION

      - name: Pousser l'image Docker
        run: |
          docker push remylt/cicd-tuto:latest
          docker push remylt/cicd-tuto:$VERSION
