name: build-docker
on: [push]

jobs: 
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.3.0

      - name: List files
        run: ls -la

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: docker push my-image:latest
